---
- name: Install Nginx on AlmaLinux with Iranian Mirrors
  hosts: targets
  become: yes

  tasks:
    - name: Clean up all repo files in yum.repos.d
      shell: rm -rf /etc/yum.repos.d/*.repo

    - name: Create repository file using template
      template:
        src: jinja.j2
        dest: /etc/yum.repos.d/almairan.repo
        owner: root
        group: root
        mode: '0644'
        
    - name: Clear DNF cache
      command: dnf clean all

    - name: makecache with retries
      command: dnf makecache
      retries: 5
      delay: 10
      register: cache_result
      until: cache_result.rc == 0

    - name: update
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Nginx directly
      dnf:
        name: nginx
        state: present
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
...